# Display
MASTER_VOLUMEN = 0.1
RESOLUTION_1080 = True
WIDTH  = 1920
HEIGHT = 1080

#WIDTH  = 1280
#HEIGHT = 720
ASPECT_RELATION_PLAYER = 2.4
ASPECT_RELATION_CHAT = 0.6
WIDTH_PLAYER_SPRITE = 100
HEIGHT_CHAT = 680
WIDTH_OBJECT = 100
WIDTH_OBJECT_ICON = 20

PLAYER_SURFACE = (WIDTH_PLAYER_SPRITE, int(WIDTH_PLAYER_SPRITE * ASPECT_RELATION_PLAYER))
CHAT_SURFACE = (int(HEIGHT_CHAT * ASPECT_RELATION_CHAT), HEIGHT_CHAT)
OBJECT_SURFACE = (WIDTH_OBJECT, WIDTH_OBJECT)
OBJECT_SURFACE_ICON = (WIDTH_OBJECT_ICON, WIDTH_OBJECT_ICON)


#Icons in the coumputer screen for Mail, Reviews, Bookings and Upgrades.
# Locations buttons
LOCATION_BUTTON_EMAIL = (760, 500)  # 720
LOCATION_BUTTON_REVIEW = (1160, 500)  # 720
LOCATION_BUTTON_BOOKING = (760, 800)  # 720
LOCATION_BUTTON_UPGRADES = (1160, 795)  # 720

#Buttons of the emails you receive
LOCATION_BUTTON_CHANGE_EMAIL_1 = (483, 205)
DISPLACEMENT_BUTTON_CHANGE = (0,75)
# LOCATION_BUTTON_CHANGE_EMAIL_2 = (150, 400)
#User name inside email button
DISPLACEMENT_NAME_BUTTON_CHANGE_EMAIL = (0, 0)


#Content of the emails
LOCATION_EMAIL_CONTENT = (889, 539)
LOCATION_EMAIL_TEXT_SUBJECT = (696, 213)
LOCATION_EMAIL_TEXT_SENDER = (696, 261)
LOCATION_EMAIL_TEXT_BODY = (739, 354)

#Response for the emails, Accept o Decline the booking
LOCATION_BUTTON_ACCEPT_BOOKING = (839, 791)
LOCATION_BUTTON_DECLINE_BOOKING = (997, 791)

#Calendar and buttons to change the month displayed
LOCATION_CALENDAR = (1395, 391)
LOCATION_BUTTON_NEXT_MONTH = (1536, 411)
LOCATION_BUTTON_PREVIOUS_MONTH = (1254, 411)

#Marker that selects the week you want to book
DISPLACEMENT_CALENDAR_MARKER_0 = (1395, 374)
DISPLACEMENT_CALENDAR_MARKER_1 = (1395, 402)
DISPLACEMENT_CALENDAR_MARKER_2 = (1395, 430)
DISPLACEMENT_CALENDAR_MARKER_3 = (1395, 458)



# Level config

# HUB









## 720
if not RESOLUTION_1080:
	LOCATION_BUTTON_EMAIL = (int(LOCATION_BUTTON_EMAIL[0] / 1.5), int(LOCATION_BUTTON_EMAIL[1] / 1.5))
if not RESOLUTION_1080:
	LOCATION_BUTTON_REVIEW = (int(LOCATION_BUTTON_REVIEW[0] / 1.5), int(LOCATION_BUTTON_REVIEW[1] / 1.5))
if not RESOLUTION_1080:
	LOCATION_BUTTON_BOOKING = (int(LOCATION_BUTTON_BOOKING[0] / 1.5), int(LOCATION_BUTTON_BOOKING[1] / 1.5))
if not RESOLUTION_1080:
	LOCATION_BUTTON_UPGRADES = (int(LOCATION_BUTTON_UPGRADES[0] / 1.5), int(LOCATION_BUTTON_UPGRADES[1] / 1.5))